[
  {  
    "photo":"https://s3-us-west-2.amazonaws.com/s.cdpn.io/49157/profile/profile-80_24.jpg",
    "name":"Manolo",
    "last":"Smith",
    "email":"jhony@site.com",
    "phone":"1-555-222-333",
    "web":"http://jhonSmith.com"
  },
  {  
    "photo":"https://s3-us-west-2.amazonaws.com/s.cdpn.io/49157/profile/profile-80_24.jpg",
    "name":"Carla",
    "last":"Doe",
    "email":"carladoe@site.com",
    "phone":"1-333-111-555",
    "web":"http://carladoe.com"
  },
  {  
    "photo":"https://s3-us-west-2.amazonaws.com/s.cdpn.io/49157/profile/profile-80_24.jpg",
    "name":"Stefan",
    "last":"Varela",
    "email":"stefano@site.com",
    "phone":"2-444-222-777",
    "web":"http://stefano.com"
  },
  {  
    "photo":"https://s3-us-west-2.amazonaws.com/s.cdpn.io/49157/profile/profile-80_24.jpg",
    "name":"Angeline",
    "last":"Julai",
    "email":"angeline@site.com",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {  
    "photo":"https://s3-us-west-2.amazonaws.com/s.cdpn.io/49157/profile/profile-80_24.jpg",
    "name":"New name",
    "last":"for test",
    "email":"angeline@site.com",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  }
]
